# Generated by Django 6.0 on 2025-12-03 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='Used', max_length=10)),
                ('features_backup_camera', models.BooleanField(default=False, verbose_name='Backup Camera')),
                ('features_bluetooth', models.BooleanField(default=False, verbose_name='Bluetooth')),
                ('features_cruise_control', models.BooleanField(default=False, verbose_name='Cruise Control')),
                ('features_gps', models.BooleanField(default=False, verbose_name='GPS / Navigation')),
                ('features_sunroof', models.BooleanField(default=False, verbose_name='Sunroof')),
                ('description', models.TextField()),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
